# Generated by Django 3.2 on 2021-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=50)),
                ('productBrand', models.CharField(max_length=50)),
                ('productColor', models.CharField(max_length=50)),
                ('productSize', models.CharField(max_length=3)),
                ('productDescription', models.CharField(max_length=100)),
                ('productImage', models.ImageField(upload_to='productImages/')),
            ],
        ),
    ]
