# Generated by Django 3.2 on 2021-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=3)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, default=1.99, max_digits=5)),
                ('product_image', models.ImageField(upload_to='loja/')),
            ],
        ),
    ]
