# Generated by Django 3.2 on 2021-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productDescription',
        ),
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='loja/productImages/'),
        ),
    ]
