# Generated by Django 3.2 on 2021-10-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_product_productimage'),
        ('loja', '0002_auto_20211001_0930'),
    ]

    operations = [
    ]
