# Generated by Django 3.2 on 2021-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_merge_20211001_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='loja/'),
        ),
    ]
