# Generated by Django 3.2 on 2021-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
